### PR TITLE
Add linkMessage utility

### PR DESCRIPTION
**Pull request by roj1512**

### CODE REVIEW

**Comment by KnightNiwrem** [comment]
@roj1512 The behavior for chatId seems awfully specific. What's the use case for a user to provide some positive chatId value, only for the library to specifically transform it into a larger negative value?

**Comment by roj1512** [comment]
@KnightNiwrem We can't link to messages of chats with positive chat IDs...

**Comment by KnightNiwrem** [comment]
> @KnightNiwrem We can't link to messages whose chats have positive IDs.

Hmm.. maybe I'm not being clear enough. Why don't we ask and expect users to provide negative chatIds then? Why are we doing the transformation for them, and under what circumstances will user provide a positive chatId when they really want to target a negative chatId?

**Comment by roj1512** [comment]
How to ask them? A comment or throw an error?

**Comment by KnightNiwrem** [comment]
> How to ask them? A comment or throw an error?

Well, to be clear, your PQ will break if the user provides the negative chatIDs to start with, since negative * -1 is positive.

That's why we want to be clear about the use cases here. We should start with:
1. What information does the user have?
2. What is the user trying to accomplish?
4. What conveniences can be reasonable expected from the user, and provided to the user, to get the user from point 1 to point 2.

If we are not clear about the use cases for the problem statement, then we wouldn't be able to formulate or validate the solutions proposed.

**Comment by roj1512** [comment]
It won't break if they provide a negative chat ID, and it is intended to provide a negative chat ID.

**Comment by roj1512** [comment]
> What information does the user have?

The user has a message object, or its ID and the ID of the supergroup/channel that it was sent in.

> What is the user trying to accomplish?

They try to link to that message without having a utility function for each of their projects.

> What conveniences can be reasonable expected from the user, and provided to the user, to get the user from point 1 to point 2.

I don't understand this.

**Comment by KnightNiwrem** [comment]
> It won't break if they provide a negative chat ID, and it is intended to provide a negative chat ID.

Reference from https://core.telegram.org/bots/api#chat:
```
Unique identifier for this chat. This number may have more than 32 significant bits and some programming languages may have difficulty/silent defects in interpreting it. But it has at most 52 significant bits, so a signed 64-bit integer or double-precision float type are safe for storing this identifier.
```

-(2^51) - 1 = -2251799813685247

Proposed change:
```typescript
const linkMessage = (stringLike: Stringable, chatId: number, messageId: number) => {
  return link(stringLike, `https://t.me/c/${(chatId+ 1000000000000) * -1}/${messageId}`)
}
```

Testing:
```typescript
const testEntityMaker = (stringLike: Stringable, chatId: number, messageId: number) => {
  return `https://t.me/c/${(chatId+ 1000000000000) * -1}/${messageId}`
}
testEntityMaker("test link", -2251799813685247, 17264);

> 'https://t.me/c/2250799813685247/17264'
```

?

**Comment by roj1512** [comment]
`2251799813685247` is not a valid chat ID tho. A supergroup/channel chat ID given by the Bot API would never look like that, will it?

**Comment by KnightNiwrem** [comment]
> `2251799813685247` is not a valid chat ID tho. A supergroup/channel chat ID given by the Bot API would never look like that, will it?

If you want it to start with -100:

```
-2251799813685247
-1009999999999999

// 1009999999999999 < 2251799813685247
> true
```

Testing:
```typescript
const testEntityMaker = (stringLike: Stringable, chatId: number, messageId: number) => {
  return `https://t.me/c/${(chatId+ 1000000000000) * -1}/${messageId}`
}
testEntityMaker("test link", -2251799813685247, 17264);

> 'https://t.me/c/1008999999999999/17264'
```

**Comment by roj1512** [comment]
What about we check if the chatId is between these two and error if it wasn't?

https://github.com/pyrogram/pyrogram/blob/6f7ec0de03a2b497d3a5c844c1c9e1ec40896483/pyrogram/utils.py#L201-L202

**Comment by KnightNiwrem** [comment]
> How about we check if the `chatId` is between these two and error if it isn't?
> 
> https://github.com/pyrogram/pyrogram/blob/6f7ec0de03a2b497d3a5c844c1c9e1ec40896483/pyrogram/utils.py#L201-L202

Isn't this old information? We should be building features using the newest information from the Bot API docs. Even if this functionality would technically work today for the millions of unmigrated chatIds, it would break eventually - and we would be knowingly writing features that we know will break.

The number `-1002147483647` would use at most 41 significant bits, give or take. That's just strictly incorrect.

**Comment by KnightNiwrem** [comment]
> How about we check if the `chatId` is between these two and error if it isn't?
> 
> https://github.com/pyrogram/pyrogram/blob/6f7ec0de03a2b497d3a5c844c1c9e1ec40896483/pyrogram/utils.py#L201-L202

I don't think we need to throw an error in this case. If we only want to support unmigrated chatIds for now, we can certainly check if the chatIds are within range, and perform the transformation if it is, or return the stringLike as-is if it isn't.

**Comment by KnightNiwrem** [comment]
> How about we check if the `chatId` is between these two and error if it isn't?
> 
> https://github.com/pyrogram/pyrogram/blob/6f7ec0de03a2b497d3a5c844c1c9e1ec40896483/pyrogram/utils.py#L201-L202

@roj1512 I've created a PQ to your branch, to implement this check at https://github.com/grammyjs/parse-mode/pull/9.

**Review by KnightNiwrem — APPROVED** [review]

**Comment by KnightNiwrem** [comment]
Published to `1.4.0`! 🎉

**Comment by roj1512** [comment]
thanks @KnightNiwrem

**Comment by KnorpelSenf** [comment]
Should this be documented somewhere beyond the API ref?

**Pull request merged**
