### PR TITLE
Draft: Tagged template based formatting

### PR DESCRIPTION
**Pull request by Loskir**
Example usage:

```ts
import {fmt, bold, italic, link} from 'parse-mode/format'

bot.on('message', (ctx) => {
  return ctx.replyFmt(fmt`${bold('bold!')}
${bold(italic('bitalic!'))}
${bold(fmt`bold ${link('blink', 'example.com')} bold`)}`)
})
```

### CODE REVIEW

**Comment by KnorpelSenf** [comment]
Is this ready for review?

**Comment by Loskir** [comment]
It is technically working, though not production-ready, I think. I'm not sure I'm going to make any further changes to this. Maybe it's worth merging this into a separate branch to discuss and develop together

**Comment by KnorpelSenf** [comment]
I see, thanks.

@KnightNiwrem you decide.

**Comment by KnightNiwrem** [comment]
I'll probably want to play around with it for a bit, which isn't soon given my current workload.

**Comment by KnorpelSenf** [comment]
Understood. Will wait for your feedback.

**Comment by KnightNiwrem** [comment]
Discussion moved to: https://github.com/grammyjs/parse-mode/pull/5

**Pull request closed without merging**
